apiVersion: v1
kind: Service
metadata:
    name: myfirst-svc-lb
spec:
    ports:
        - name: myfirst-port
          port: 3000
          targetPort: 3000
    selector:
        app.kubernetes.io/instance: myfirst-deployment
    type: LoadBalancer
