apiVersion: v1
kind: Pod
metadata:
    name: myfirst-pod-example2
spec:
    containers:
        - name: myfirst-pod
          image: busybox
          args: ['tail', '-f', '/dev/null']
          volumeMounts:
              - name: cm-volume
                mountPath: /etc/config

    volumes:
        - name: cm-volume
          configMap:
              name: myfirst-configmap
              items:
                  - key: age
                    path: age_custom
