apiVersion: v1
kind: Pod
metadata:
    name: myfirst-pod-example
spec:
    containers:
    - name: myfirst-pod
      image: busybox
      args: ['tail', '-f', '/dev/null']
      envFrom:
      - configMapRef:
          name: myfirst-configmap

